### PR TITLE
feat(prefillEnabled) add prefill & code refactors for async local storage and hoisted functions/global variables

### PR DESCRIPTION
**Pull request by gitmotion**
Added Enable Prefill with Url ~~and Enable Dark Mode~~ Options / Checkboxes: 
- for more customizability and quality of life improvements
- refactored code so it's more extensible and reusable

| Feature / Update | Description |
|---|---|
| Enable Prefill with URL Option | - Checkbox allowing users to enable/disable adding the page URL to the message. <br> - Useful for sending notifications without the URL. (Saves to storage) |
| **Prefill Functionality** | - Unchecking/checking the checkbox and saving the config updates the message in real-time. <br> - Removes or appends the page URL to the message beginning. <br> - Prevents duplicate removals/additions if the message is edited before saving config. |
| ~~**Enable Dark Mode**~~ | ~~- Checkbox allowing users to enable/disable dark mode for the extension's UI. (Saves to storage)~~ |
| Refactored popup.js | - Hoisted functions and global variables for execution before declaration. <br> - Enables asynchronous functionality by retrieving data from storage once. <br> - Previously called `chrome.storage.sync.get()` three times, now called once onload and stores values in global variables. |
| Modularized Functions | - Improved extensibility by modularizing functions. <br> - Allows independent function calls (e.g., `getConfigs`, `saveConfig`, `updateUI`, `showStatus`, `showWarning`, etc.) from anywhere. <br> - Facilitates future refactoring into separate files. |
| Retained Functionality | - All previous functionalities are maintained and tested. |

##

| Screenshot | Demo |
|---|---|
| <a href="https://github.com/user-attachments/assets/96021502-ccb8-41b4-8af5-a6d5a6d31aa1" target="_blank"></a> | <a href="https://github.com/user-attachments/assets/10e70aa5-65d3-4494-bb5a-0eccb7618002" target="_blank"></a> |

### Revised
- removed Enable dark mode option
image

### CODE REVIEW

**Comment by TheDuffman85** [comment]
Thank you for your comprehensive contribution. I appreciate the refactoring and the possibility to disable prefill. But I don't feel that it is necessary to add a button to enable or disable dark mode. The idea is, that the extension follows the current browser settings. It's working fine in Firefox, but for some reason it's not working in Chrome based browsers. Maybe we should try to fix that behavior?

**Comment by gitmotion** [comment]
@TheDuffman85 thanks for the feedback! no worries might've been a lot of changes at once. updated the code to address the following comments:
(tldr: for now i removed the dark mode and thinking we can address the light mode issue in chrome separately👍)

> But I don't feel that it is necessary to add a button to enable or disable dark mode.
- removed the dark mode options and reverted those functions
- retested and everything should be working as expected

> It's working fine in Firefox, but for some reason it's not working in Chrome based browsers. Maybe we should try to fix that behavior?
- for this i'm thinking addressing this separately would be better in a different PR so i'll try to take a look at that later when i have the chance!

i rebased my changes so that it all stays in one commit instead of multiple to keep it tight

**Comment by TheDuffman85** [comment]
Sounds good! I've tested your code. Seems to work fine. I'll merge it and prepare a new release.

**Comment by TheDuffman85** [comment]
I've published a new version of the add-on to the browser stores. It can take up to 30 days to get it approved. Thank you  again for your contribution.

**Comment by gitmotion** [comment]
@TheDuffman85 amazing looking forward to it! thank you 🙏

**Pull request merged**
